# Generated by Django 4.2 on 2023-06-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacher", "0002_teacher_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="photo",
            field=models.ImageField(null=True, upload_to="photo/teachers"),
        ),
    ]
