# Generated by Django 4.2 on 2023-06-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacher", "0003_alter_teacher_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="photo",
            field=models.ImageField(
                default="photo/teachers/default_teacher_avatar.jpg",
                null=True,
                upload_to="photo/teachers",
            ),
        ),
    ]
