# Generated by Django 4.2 on 2023-05-04 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "execution_time",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 5, 5, 0, 35, 30, 169394)
                    ),
                ),
                ("request_path", models.CharField(max_length=100)),
                ("request_method", models.CharField(max_length=40)),
            ],
        ),
    ]
