# Generated by Django 4.2 on 2023-05-06 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="execution_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 6, 10, 44, 29, 824652, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
