# Generated by Django 4.2 on 2023-05-30 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log", "0002_alter_log_execution_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="execution_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 30, 21, 50, 57, 600158, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
