# Generated by Django 4.2 on 2023-06-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0002_student_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="foto",
            field=models.ImageField(null=True, upload_to="photo/students"),
        ),
    ]
