# Generated by Django 4.2 on 2023-06-13 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0003_student_foto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="foto",
            new_name="photo",
        ),
    ]
