# Generated by Django 4.2 on 2023-06-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0004_rename_foto_student_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="photo",
            field=models.ImageField(
                default="photo/students/default_student_avatar.jpg",
                null=True,
                upload_to="photo/students",
            ),
        ),
    ]
